# Generated by Django 3.2 on 2022-05-09 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fvid_length', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_nodes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('upload_frequency', models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1)])),
                ('next_fvid_to_analyze', models.TextField(blank=True, null=True)),
                ('percentage', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
