# Generated by Django 3.2 on 2022-05-09 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fvid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjacencyMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('number_of_nodes', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FVIDAdjacencyMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjacency_matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adjacency_matrix.adjacencymatrix')),
                ('fvid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fvid.fvid')),
            ],
            options={
                'unique_together': {('fvid', 'adjacency_matrix')},
            },
        ),
    ]
