# Generated by Django 3.2 on 2023-05-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjacency_matrix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjacencymatrix',
            name='fvids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
